[package]
name = "comet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"
libc = "0.2.98"
modular-bitfield = "0.11.2"
generic_static = "0.2.0"
atomic = "0.5.0"
backtrace = "*"
crossbeam-utils = "0.8"

[target.'cfg(not(wasm))'.dependencies]
memmap2 = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "memoryapi",
    "winnt",
    "sysinfoapi",
    "minwinbase",
    "errhandlingapi",
    "excpt",
    "minwindef",
    "wincrypt",
] }
